apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
  labels:
    app: wil-playground
spec:
  selector:
    app: wil-playground
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP  # ou NodePort selon vos besoins